services:

  mongodb:

    image: mongo:8
    container_name: notes-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:

    build:
      context: ./Backend
    image: notes-backend
    container_name: notes-backend-container
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/notesdb
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
  
    build:
      context: ./Frontend
    image: notes-frontend
    container_name: notes-frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
  
  node-exporter:

    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
  
  prometheus:

    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:

    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  mongodb_data:
  grafana_data: