name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Azure

        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}

          script: |

            cd ~/Notes_Practice

            git pull origin main

            docker compose down

            docker compose up --build -d

            docker image prune -f